#!/usr/bin/env bash

# Based off of https://github.com/Shringe/dunst-media-control

volume_step=5
brightness_step=5
max_volume=150
notification_timeout=1000 # in milliseconds
icon_theme_dir="/run/current-system/sw/share/icons/Chicago95/status/32"

get_volume() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}'
}

is_muted() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep "MUTED" >/dev/null
}

get_brightness() {
    awk \
        -v c="$(brightnessctl get)" \
        -v m="$(brightnessctl max)" \
        'BEGIN {printf "%.0f", (c/m)*100}'
}

show_volume_notif() {
    local icon volume=$(get_volume)

    if is_muted || ((volume == 0)); then
        icon="${icon_theme_dir}/audio-volume-muted.png"
    elif ((volume < 30)); then
        icon="${icon_theme_dir}/audio-volume-low.png"
    elif ((volume < 80)); then
        icon="${icon_theme_dir}/audio-volume-medium.png"
    else
        icon="${icon_theme_dir}/audio-volume-high.png"
    fi

    notify-send \
        --icon="$icon" \
        --expire-time "$notification_timeout" \
        --hint string:x-dunst-stack-tag:volume_notif \
        --hint int:value:"$volume" \
        "${volume}%"
}

show_brightness_notif() {
    local brightness=$(get_brightness)

    notify-send \
        --icon="${icon_theme_dir}/display-brightness.png" \
        --expire-time "$notification_timeout" \
        --hint string:x-dunst-stack-tag:brightness_notif \
        --hint int:value:"$brightness" \
        "${brightness}%"
}

case $1 in
volume_up)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 # Unmute
    volume=$(get_volume)
    if (((volume + volume_step) > max_volume)); then
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "${max_volume}%"
    else
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "${volume_step}%+"
    fi
    show_volume_notif
    ;;

volume_down)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "${volume_step}%-"
    show_volume_notif
    ;;

volume_mute)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    show_volume_notif
    ;;

brightness_up)
    brightnessctl set "+${brightness_step}%"
    show_brightness_notif
    ;;

brightness_down)
    brightnessctl set "${brightness_step}%-"
    show_brightness_notif
    ;;
esac
