[manager]
show_hidden = true

[opener]
open_image = [
	{ run = 'feh --force-aliasing $1', desc = "Open with feh", for = "unix" },
]
edit_image = [
	{ run = 'gimp $1', desc = "Edit with gimp", for = "unix" },
]

[open]
rules = [
	{ mime = "image/*", use = [ "open_image", "edit_image", "reveal" ] },
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
]
